# Generated by Django 3.1.6 on 2021-06-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('no_plate', models.IntegerField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=12)),
            ],
        ),
    ]
